site_name: Qumico
# Project information
site_name: 'Qumico'
site_description: 'Documents for Qumico project'
site_author: 'Pasonatech, inc'

# Copyright
copyright: 'Copyright (c) 2019'

# Documentation and theme
docs_dir: 'docs'
theme: 'material'

# Options
extra:

  palette:
    primary: 'Light Blue'
    accent: 'Orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'yourName'
    twitter: 'yourName'

# Extensions
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: '#'

nav:
  - Home: index.md
  - インストール方法: install/install.md
  - サンプルの動作: 
    - サンプルの説明: samples/sample.md
    - MLP: samples/mlp.md
    - Convolution: samples/conv.md
    - VGG16: samples/vgg16.md
    - MobileNet: samples/mobilenet.md
    - Tiny-YOLO TensorFlow版: samples/tiny_yolo.md
    - Tiny-YOLO Darknet版: samples/tiny_yolo_yad2k.md
    - AutoML 識別: samples/automl_dogcat.md
  - 出力ファイル: output/output.md
  - APIs: API/api.md
  - Util関数:
    - annotation_dataset_tool: utils/annotation_dataset_tool.md
    - common_tool: utils/common_tool.md
    - data_aug_bbox: utils/data_aug_bbox.md
    - data_augument_tool: utils/data_augument_tool.md
    - dataset_tool: utils/dataset_tool.md
    - image_tool: utils/image_tool.md
    - pre_process_tool:  utils/pre_process_tool.md
    - tensorflow_yolo_ext: utils/tensorflow_yolo_ext.md
  - FAQ: FAQ/faq.md

repo_url: 'https://github.com/PasonaTech-Inc/Qumico'


